//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adjudicada.
        /// </summary>
        internal static string Adjudicada
        {
            get
            {
                return ResourceManager.GetString("Adjudicada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string Admin
        {
            get
            {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Administrativo.
        /// </summary>
        internal static string Administrativo
        {
            get
            {
                return ResourceManager.GetString("Administrativo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string Advertencia
        {
            get
            {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string Apellido
        {
            get
            {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Artículo.
        /// </summary>
        internal static string Articulo
        {
            get
            {
                return ResourceManager.GetString("Articulo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back
        {
            get
            {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Borrador.
        /// </summary>
        internal static string Borrador
        {
            get
            {
                return ResourceManager.GetString("Borrador", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calificación.
        /// </summary>
        internal static string Calificacion
        {
            get
            {
                return ResourceManager.GetString("Calificacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        internal static string Cantidad
        {
            get
            {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string Ciudad
        {
            get
            {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string Supervisor
        {
            get
            {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Codigo Publicación.
        /// </summary>
        internal static string CodigoPublicacion
        {
            get
            {
                return ResourceManager.GetString("CodigoPublicacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compra.
        /// </summary>
        internal static string Compra
        {
            get
            {
                return ResourceManager.GetString("Compra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compra Inmediata.
        /// </summary>
        internal static string CompraInmediata
        {
            get
            {
                return ResourceManager.GetString("CompraInmediata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        internal static string Comprar
        {
            get
            {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contacte al administrador..
        /// </summary>
        internal static string ContactarAdministrador
        {
            get
            {
                return ResourceManager.GetString("ContactarAdministrador", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        internal static string ContraseñaIncorrecta
        {
            get
            {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CUIL.
        /// </summary>
        internal static string CUIL
        {
            get
            {
                return ResourceManager.GetString("CUIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CUIT.
        /// </summary>
        internal static string CUIT
        {
            get
            {
                return ResourceManager.GetString("CUIT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Descripcion
        {
            get
            {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Descripción Corta.
        /// </summary>
        internal static string DescripcionCorta
        {
            get
            {
                return ResourceManager.GetString("DescripcionCorta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Descripción Larga.
        /// </summary>
        internal static string DescripcionLarga
        {
            get
            {
                return ResourceManager.GetString("DescripcionLarga", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detalles de Compra.
        /// </summary>
        internal static string DetallesDeCompra
        {
            get
            {
                return ResourceManager.GetString("DetallesDeCompra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detalles de Subasta.
        /// </summary>
        internal static string DetallesSubasta
        {
            get
            {
                return ResourceManager.GetString("DetallesSubasta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        internal static string DNI
        {
            get
            {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edición de Rol.
        /// </summary>
        internal static string EdicionRol
        {
            get
            {
                return ResourceManager.GetString("EdicionRol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edición de Usuario.
        /// </summary>
        internal static string EdicionUsuario
        {
            get
            {
                return ResourceManager.GetString("EdicionUsuario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edición de Visibilidad.
        /// </summary>
        internal static string EdicionVisibilidad
        {
            get
            {
                return ResourceManager.GetString("EdicionVisibilidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Componentes Electrónicos.
        /// </summary>
        internal static string Electronicos
        {
            get
            {
                return ResourceManager.GetString("Electronicos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string Empresa
        {
            get
            {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La funcionalidad seleccionada ya fue agregada..
        /// </summary>
        internal static string ErrorAgregarFuncionalidad
        {
            get
            {
                return ResourceManager.GetString("ErrorAgregarFuncionalidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol seleccionado ya fue agregado..
        /// </summary>
        internal static string ErrorAgregarRol
        {
            get
            {
                return ResourceManager.GetString("ErrorAgregarRol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo año no puede estar vacio..
        /// </summary>
        internal static string ErrorAnio
        {
            get
            {
                return ResourceManager.GetString("ErrorAnio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Apellido&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorApellido
        {
            get
            {
                return ResourceManager.GetString("ErrorApellido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar establecer conexión con la base de datos..
        /// </summary>
        internal static string ErrorBD
        {
            get
            {
                return ResourceManager.GetString("ErrorBD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar iniciar la transacción..
        /// </summary>
        internal static string ErrorBeginTrans
        {
            get
            {
                return ResourceManager.GetString("ErrorBeginTrans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error al borrar.
        /// </summary>
        internal static string ErrorBorrado
        {
            get
            {
                return ResourceManager.GetString("ErrorBorrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calificaciones pendientes.
        /// </summary>
        internal static string ErrorCalificacionesPendientes
        {
            get
            {
                return ResourceManager.GetString("ErrorCalificacionesPendientes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Calle&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorCalle
        {
            get
            {
                return ResourceManager.GetString("ErrorCalle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ya existe un cliente con el mismo tipo y número de documento..
        /// </summary>
        internal static string ErrorClienteExistente
        {
            get
            {
                return ResourceManager.GetString("ErrorClienteExistente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error al comprar.
        /// </summary>
        internal static string ErrorCompra
        {
            get
            {
                return ResourceManager.GetString("ErrorCompra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;CP&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorCp
        {
            get
            {
                return ResourceManager.GetString("ErrorCp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;CUIT&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorCuit
        {
            get
            {
                return ResourceManager.GetString("ErrorCuit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error de datos.
        /// </summary>
        internal static string ErrorDeDatos
        {
            get
            {
                return ResourceManager.GetString("ErrorDeDatos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Descripción corta&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionCortaVacia
        {
            get
            {
                return ResourceManager.GetString("ErrorDescripcionCortaVacia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Descripción larga&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionLargaVacia
        {
            get
            {
                return ResourceManager.GetString("ErrorDescripcionLargaVacia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Descripción&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionVacia
        {
            get
            {
                return ResourceManager.GetString("ErrorDescripcionVacia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;N° Doc.&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDNI
        {
            get
            {
                return ResourceManager.GetString("ErrorDNI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Email&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorEmail
        {
            get
            {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ya existe una empresa con el mismo número de CUIT..
        /// </summary>
        internal static string ErrorEmpresaExistenteCUIT
        {
            get
            {
                return ResourceManager.GetString("ErrorEmpresaExistenteCUIT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ya existe una empresa con la misma razón social..
        /// </summary>
        internal static string ErrorEmpresaExistenteRazonSocial
        {
            get
            {
                return ResourceManager.GetString("ErrorEmpresaExistenteRazonSocial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar finalizar la transacción..
        /// </summary>
        internal static string ErrorEndTrans
        {
            get
            {
                return ResourceManager.GetString("ErrorEndTrans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error en la operación.
        /// </summary>
        internal static string ErrorEnLaOperacion
        {
            get
            {
                return ResourceManager.GetString("ErrorEnLaOperacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Estado&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorEstadoVacio
        {
            get
            {
                return ResourceManager.GetString("ErrorEstadoVacio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La Fecha de Inicio no puede ser menor a la del sistema..
        /// </summary>
        internal static string ErrorFechaInicio
        {
            get
            {
                return ResourceManager.GetString("ErrorFechaInicio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La fecha de nacimiento debe ser anterior a la fecha del día de hoy..
        /// </summary>
        internal static string ErrorFechaNacimiento
        {
            get
            {
                return ResourceManager.GetString("ErrorFechaNacimiento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La fecha ingresada en el archivo de configuración no es válida..
        /// </summary>
        internal static string ErrorFechaSistema
        {
            get
            {
                return ResourceManager.GetString("ErrorFechaSistema", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La Fecha de Vencimiento no puede ser menor a la del sistema..
        /// </summary>
        internal static string ErrorFechaVencimiento
        {
            get
            {
                return ResourceManager.GetString("ErrorFechaVencimiento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error al guardar.
        /// </summary>
        internal static string ErrorGuardado
        {
            get
            {
                return ResourceManager.GetString("ErrorGuardado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Todo rol debe tener la funcionalidad &quot;Login y Seguridad&quot;..
        /// </summary>
        internal static string ErrorLoginSeguridad
        {
            get
            {
                return ResourceManager.GetString("ErrorLoginSeguridad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se ha instanciado ninguna conexión..
        /// </summary>
        internal static string ErrorNoConnection
        {
            get
            {
                return ResourceManager.GetString("ErrorNoConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El código ingresado no corresponde a ninguna publicación existente en el sistema o corresponde a una generada por otro usuario..
        /// </summary>
        internal static string ErrorNoExisteCodPublicacion
        {
            get
            {
                return ResourceManager.GetString("ErrorNoExisteCodPublicacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Nombre&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorNombre
        {
            get
            {
                return ResourceManager.GetString("ErrorNombre", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se ha instanciado ninguna transacción..
        /// </summary>
        internal static string ErrorNoTrans
        {
            get
            {
                return ResourceManager.GetString("ErrorNoTrans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;N°&quot; no puede estar vacio..
        /// </summary>
        internal static string ErrorNumeroCalle
        {
            get
            {
                return ResourceManager.GetString("ErrorNumeroCalle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El valor de la oferta no puede ser menor al precio actual de la subasta..
        /// </summary>
        internal static string ErrorOferta
        {
            get
            {
                return ResourceManager.GetString("ErrorOferta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Password&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorPassword
        {
            get
            {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Las empresas sólo pueden publicar productos del rubro &quot;Componentes Electrónicos&quot;.
        /// </summary>
        internal static string ErrorPublicacionEmpresa
        {
            get
            {
                return ResourceManager.GetString("ErrorPublicacionEmpresa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La publicación se encuentra pausada.
        /// </summary>
        internal static string ErrorPublicacionPausada
        {
            get
            {
                return ResourceManager.GetString("ErrorPublicacionPausada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Razón Social&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorRazonSocial
        {
            get
            {
                return ResourceManager.GetString("ErrorRazonSocial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol que se desea borrar es el único que los siguientes usuarios tienen asignado:.
        /// </summary>
        internal static string ErrorRolBorrado1
        {
            get
            {
                return ResourceManager.GetString("ErrorRolBorrado1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Existen varios usuarios cuyo único rol asignado es el que se desea borrar..
        /// </summary>
        internal static string ErrorRolBorrado2
        {
            get
            {
                return ResourceManager.GetString("ErrorRolBorrado2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol ya ha sido dado de baja..
        /// </summary>
        internal static string ErrorRolBorrado3
        {
            get
            {
                return ResourceManager.GetString("ErrorRolBorrado3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ya existe un rol con la descripción ingresada..
        /// </summary>
        internal static string ErrorRolExistente
        {
            get
            {
                return ResourceManager.GetString("ErrorRolExistente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar deshacer la transacción..
        /// </summary>
        internal static string ErrorRollbackTrans
        {
            get
            {
                return ResourceManager.GetString("ErrorRollbackTrans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol debe tener al menos una funcionalidad..
        /// </summary>
        internal static string ErrorRolSinFuncionalidad
        {
            get
            {
                return ResourceManager.GetString("ErrorRolSinFuncionalidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar ejecutar el stored procedure..
        /// </summary>
        internal static string ErrorSP
        {
            get
            {
                return ResourceManager.GetString("ErrorSP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La cantidad a comprar no puede superar el stock..
        /// </summary>
        internal static string ErrorStock
        {
            get
            {
                return ResourceManager.GetString("ErrorStock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Tipo Doc.&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorTipoDocumento1
        {
            get
            {
                return ResourceManager.GetString("ErrorTipoDocumento1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El tipo de documento debe ser DNI, LE o CUIL..
        /// </summary>
        internal static string ErrorTipoDocumento2
        {
            get
            {
                return ResourceManager.GetString("ErrorTipoDocumento2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar ejecutar la transacción..
        /// </summary>
        internal static string ErrorTrans
        {
            get
            {
                return ResourceManager.GetString("ErrorTrans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;Username&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorUserName
        {
            get
            {
                return ResourceManager.GetString("ErrorUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario ya ha sido dado de baja..
        /// </summary>
        internal static string ErrorUsuarioBorrado
        {
            get
            {
                return ResourceManager.GetString("ErrorUsuarioBorrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El autor de una publicación no puede Comprar/Ofertar sobre la misma..
        /// </summary>
        internal static string ErrorUsuarioCompraSuPublicacion
        {
            get
            {
                return ResourceManager.GetString("ErrorUsuarioCompraSuPublicacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Todo usuario debe tener un rol &quot;Usuario&quot; o &quot;Empresa&quot;..
        /// </summary>
        internal static string ErrorUsuarioRol
        {
            get
            {
                return ResourceManager.GetString("ErrorUsuarioRol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La visibilidad que desea borrar está siendo usada por una publicación..
        /// </summary>
        internal static string ErrorVisibilidadBorrada
        {
            get
            {
                return ResourceManager.GetString("ErrorVisibilidadBorrada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ya existe una visibilidad con la descripción ingresada..
        /// </summary>
        internal static string ErrorVisibilidadExistente
        {
            get
            {
                return ResourceManager.GetString("ErrorVisibilidadExistente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string Estado
        {
            get
            {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fastforward
        {
            get
            {
                object obj = ResourceManager.GetObject("fastforward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fastreverse
        {
            get
            {
                object obj = ResourceManager.GetObject("fastreverse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Fecha
        {
            get
            {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        internal static string FechaInicio
        {
            get
            {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fecha Vencimiento.
        /// </summary>
        internal static string FechaVencimiento
        {
            get
            {
                return ResourceManager.GetString("FechaVencimiento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forward
        {
            get
            {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Funcionalidad.
        /// </summary>
        internal static string Funcionalidad
        {
            get
            {
                return ResourceManager.GetString("Funcionalidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID Compra.
        /// </summary>
        internal static string IdCompra
        {
            get
            {
                return ResourceManager.GetString("IdCompra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID Compra/ID Oferta.
        /// </summary>
        internal static string IdCompraIdOferta
        {
            get
            {
                return ResourceManager.GetString("IdCompraIdOferta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código Factura.
        /// </summary>
        internal static string IdFactura
        {
            get
            {
                return ResourceManager.GetString("IdFactura", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código Publicacion.
        /// </summary>
        internal static string IdPublicacion
        {
            get
            {
                return ResourceManager.GetString("IdPublicacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID Usuario.
        /// </summary>
        internal static string IdUsuario
        {
            get
            {
                return ResourceManager.GetString("IdUsuario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Intentos restantes: .
        /// </summary>
        internal static string IntentosRestantes
        {
            get
            {
                return ResourceManager.GetString("IntentosRestantes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LE.
        /// </summary>
        internal static string LE
        {
            get
            {
                return ResourceManager.GetString("LE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        internal static string Localidad
        {
            get
            {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login y Seguridad.
        /// </summary>
        internal static string LoginSeguridad
        {
            get
            {
                return ResourceManager.GetString("LoginSeguridad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gracias por su visita, ¡lo esperamos de vuelta!.
        /// </summary>
        internal static string MensajeDespedida
        {
            get
            {
                return ResourceManager.GetString("MensajeDespedida", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MercadoEnvío.
        /// </summary>
        internal static string ABM
        {
            get
            {
                return ResourceManager.GetString("ABM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string Monto
        {
            get
            {
                return ResourceManager.GetString("Monto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monto Facturado.
        /// </summary>
        internal static string MontoFacturado
        {
            get
            {
                return ResourceManager.GetString("MontoFacturado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monto/Oferta.
        /// </summary>
        internal static string MontoOferta
        {
            get
            {
                return ResourceManager.GetString("MontoOferta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to N° Doc..
        /// </summary>
        internal static string NoDoc
        {
            get
            {
                return ResourceManager.GetString("NoDoc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nombre
        {
            get
            {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nombre del usuario.
        /// </summary>
        internal static string NombreUsuario
        {
            get
            {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se ha generado la compra N° .
        /// </summary>
        internal static string NroCompra
        {
            get
            {
                return ResourceManager.GetString("NroCompra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ha reservado la compra del producto. Se ha generado la compra N° .
        /// </summary>
        internal static string NroCompraPrecioReserva
        {
            get
            {
                return ResourceManager.GetString("NroCompraPrecioReserva", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se ha generado la oferta N°.
        /// </summary>
        internal static string NroOferta
        {
            get
            {
                return ResourceManager.GetString("NroOferta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se ha generado la publicación N° .
        /// </summary>
        internal static string NroPublicacion
        {
            get
            {
                return ResourceManager.GetString("NroPublicacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        internal static string Observacion
        {
            get
            {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ofertar.
        /// </summary>
        internal static string Ofertar
        {
            get
            {
                return ResourceManager.GetString("Ofertar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operación Exitosa.
        /// </summary>
        internal static string OperacionExitosa
        {
            get
            {
                return ResourceManager.GetString("OperacionExitosa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pausada.
        /// </summary>
        internal static string Pausada
        {
            get
            {
                return ResourceManager.GetString("Pausada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        internal static string Porcentaje
        {
            get
            {
                return ResourceManager.GetString("Porcentaje", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Porcentaje Envío.
        /// </summary>
        internal static string PorcentajeEnvio
        {
            get
            {
                return ResourceManager.GetString("PorcentajeEnvio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string Precio
        {
            get
            {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El precio del producto debe ser mayor a 0..
        /// </summary>
        internal static string PrecioInvalido
        {
            get
            {
                return ResourceManager.GetString("PrecioInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El precio de reserva de la subasta debe ser mayor a 0..
        /// </summary>
        internal static string PrecioReservaInvalido
        {
            get
            {
                return ResourceManager.GetString("PrecioReservaInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La publicación ha sido actualizada exitosamente..
        /// </summary>
        internal static string PublicacionActualizada
        {
            get
            {
                return ResourceManager.GetString("PublicacionActualizada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to R.Social.
        /// </summary>
        internal static string RazonSocial
        {
            get
            {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resultados para el Rubro: .
        /// </summary>
        internal static string ResultadosRubro
        {
            get
            {
                return ResourceManager.GetString("ResultadosRubro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string Rol
        {
            get
            {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol ha sido actualizado exitosamente..
        /// </summary>
        internal static string RolActualizado
        {
            get
            {
                return ResourceManager.GetString("RolActualizado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol ha sido borrado exitosamente..
        /// </summary>
        internal static string RolBorrado
        {
            get
            {
                return ResourceManager.GetString("RolBorrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol ha sido creado exitosamente..
        /// </summary>
        internal static string RolCreado
        {
            get
            {
                return ResourceManager.GetString("RolCreado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rubro.
        /// </summary>
        internal static string Rubro
        {
            get
            {
                return ResourceManager.GetString("Rubro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rubro ha sido creado exitosamente..
        /// </summary>
        internal static string RubroCreado
        {
            get
            {
                return ResourceManager.GetString("RubroCreado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stock
        {
            get
            {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El stock debe ser mayor a 0..
        /// </summary>
        internal static string StockInvalido
        {
            get
            {
                return ResourceManager.GetString("StockInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subasta.
        /// </summary>
        internal static string Subasta
        {
            get
            {
                return ResourceManager.GetString("Subasta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clientes con mayor cantidad de productos comprados.
        /// </summary>
        internal static string TipoListadoClientesMasProductos
        {
            get
            {
                return ResourceManager.GetString("TipoListadoClientesMasProductos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vendedores con mayor cantidad de facturas.
        /// </summary>
        internal static string TipoListadoVendedoresMasFacturas
        {
            get
            {
                return ResourceManager.GetString("TipoListadoVendedoresMasFacturas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vendedores con mayor monto facturado.
        /// </summary>
        internal static string TipoListadoVendedoresMasMonto
        {
            get
            {
                return ResourceManager.GetString("TipoListadoVendedoresMasMonto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vendedores con mayor cantidad de productos no vendidos.
        /// </summary>
        internal static string TipoListadoVendedoresProductosNoVendidos
        {
            get
            {
                return ResourceManager.GetString("TipoListadoVendedoresProductosNoVendidos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo de Publicación.
        /// </summary>
        internal static string TipoPublicacion
        {
            get
            {
                return ResourceManager.GetString("TipoPublicacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compra.
        /// </summary>
        internal static string TituloCompra
        {
            get
            {
                return ResourceManager.GetString("TituloCompra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total
        {
            get
            {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido actualizado exitosamente..
        /// </summary>
        internal static string UsuarioActualizado
        {
            get
            {
                return ResourceManager.GetString("UsuarioActualizado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuario bloqueado. .
        /// </summary>
        internal static string UsuarioBloqueado
        {
            get
            {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido borrado exitosamente..
        /// </summary>
        internal static string UsuarioBorrado
        {
            get
            {
                return ResourceManager.GetString("UsuarioBorrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido creado exitosamente..
        /// </summary>
        internal static string UsuarioCreado
        {
            get
            {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuario deshabilitado. .
        /// </summary>
        internal static string UsuarioDeshabilitado
        {
            get
            {
                return ResourceManager.GetString("UsuarioDeshabilitado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario ingresado no existe..
        /// </summary>
        internal static string UsuarioNoExiste
        {
            get
            {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vendedor.
        /// </summary>
        internal static string Vendedor
        {
            get
            {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visibilidad.
        /// </summary>
        internal static string Visibilidad
        {
            get
            {
                return ResourceManager.GetString("Visibilidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La visibilidad ha sido actualizada exitosamente..
        /// </summary>
        internal static string VisibilidadActualizada
        {
            get
            {
                return ResourceManager.GetString("VisibilidadActualizada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La visibilidad ha sido borrada exitosamente..
        /// </summary>
        internal static string VisibilidadBorrada
        {
            get
            {
                return ResourceManager.GetString("VisibilidadBorrada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La visibilidad ha sido creada exitosamente..
        /// </summary>
        internal static string VisibilidadCreada
        {
            get
            {
                return ResourceManager.GetString("VisibilidadCreada", resourceCulture);
            }
        }
    }
}
