//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjudicada.
        /// </summary>
        internal static string Adjudicada {
            get {
                return ResourceManager.GetString("Adjudicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrativo.
        /// </summary>
        internal static string Administrativo {
            get {
                return ResourceManager.GetString("Administrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo.
        /// </summary>
        internal static string Articulo {
            get {
                return ResourceManager.GetString("Articulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrador.
        /// </summary>
        internal static string Borrador {
            get {
                return ResourceManager.GetString("Borrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificación.
        /// </summary>
        internal static string Calificacion {
            get {
                return ResourceManager.GetString("Calificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Publicación.
        /// </summary>
        internal static string CodigoPublicacion {
            get {
                return ResourceManager.GetString("CodigoPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compra.
        /// </summary>
        internal static string Compra {
            get {
                return ResourceManager.GetString("Compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compra Inmediata.
        /// </summary>
        internal static string CompraInmediata {
            get {
                return ResourceManager.GetString("CompraInmediata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacte al administrador..
        /// </summary>
        internal static string ContactarAdministrador {
            get {
                return ResourceManager.GetString("ContactarAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        internal static string ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIL.
        /// </summary>
        internal static string CUIL {
            get {
                return ResourceManager.GetString("CUIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIT.
        /// </summary>
        internal static string CUIT {
            get {
                return ResourceManager.GetString("CUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Corta.
        /// </summary>
        internal static string DescripcionCorta {
            get {
                return ResourceManager.GetString("DescripcionCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Larga.
        /// </summary>
        internal static string DescripcionLarga {
            get {
                return ResourceManager.GetString("DescripcionLarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de Compra.
        /// </summary>
        internal static string DetallesDeCompra {
            get {
                return ResourceManager.GetString("DetallesDeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de Subasta.
        /// </summary>
        internal static string DetallesSubasta {
            get {
                return ResourceManager.GetString("DetallesSubasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de Rol.
        /// </summary>
        internal static string EdicionRol {
            get {
                return ResourceManager.GetString("EdicionRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de Usuario.
        /// </summary>
        internal static string EdicionUsuario {
            get {
                return ResourceManager.GetString("EdicionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de Visibilidad.
        /// </summary>
        internal static string EdicionVisibilidad {
            get {
                return ResourceManager.GetString("EdicionVisibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componentes Electrónicos.
        /// </summary>
        internal static string Electronicos {
            get {
                return ResourceManager.GetString("Electronicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        internal static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La funcionalidad seleccionada ya fue agregada..
        /// </summary>
        internal static string ErrorAgregarFuncionalidad {
            get {
                return ResourceManager.GetString("ErrorAgregarFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol seleccionado ya fue agregado..
        /// </summary>
        internal static string ErrorAgregarRol {
            get {
                return ResourceManager.GetString("ErrorAgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo año no puede estar vacio..
        /// </summary>
        internal static string ErrorAnio {
            get {
                return ResourceManager.GetString("ErrorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Apellido&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorApellido {
            get {
                return ResourceManager.GetString("ErrorApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar establecer conexión con la base de datos..
        /// </summary>
        internal static string ErrorBD {
            get {
                return ResourceManager.GetString("ErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar iniciar la transacción..
        /// </summary>
        internal static string ErrorBeginTrans {
            get {
                return ResourceManager.GetString("ErrorBeginTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al borrar.
        /// </summary>
        internal static string ErrorBorrado {
            get {
                return ResourceManager.GetString("ErrorBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificaciones pendientes.
        /// </summary>
        internal static string ErrorCalificacionesPendientes {
            get {
                return ResourceManager.GetString("ErrorCalificacionesPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Calle&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorCalle {
            get {
                return ResourceManager.GetString("ErrorCalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un cliente con el mismo tipo y número de documento..
        /// </summary>
        internal static string ErrorClienteExistente {
            get {
                return ResourceManager.GetString("ErrorClienteExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al comprar.
        /// </summary>
        internal static string ErrorCompra {
            get {
                return ResourceManager.GetString("ErrorCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;CP&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorCp {
            get {
                return ResourceManager.GetString("ErrorCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;CUIT&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorCuit {
            get {
                return ResourceManager.GetString("ErrorCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de datos.
        /// </summary>
        internal static string ErrorDeDatos {
            get {
                return ResourceManager.GetString("ErrorDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Descripción corta&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionCortaVacia {
            get {
                return ResourceManager.GetString("ErrorDescripcionCortaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Descripción larga&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionLargaVacia {
            get {
                return ResourceManager.GetString("ErrorDescripcionLargaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Descripción&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDescripcionVacia {
            get {
                return ResourceManager.GetString("ErrorDescripcionVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;N° Doc.&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorDNI {
            get {
                return ResourceManager.GetString("ErrorDNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Email&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una empresa con el mismo número de CUIT..
        /// </summary>
        internal static string ErrorEmpresaExistenteCUIT {
            get {
                return ResourceManager.GetString("ErrorEmpresaExistenteCUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una empresa con la misma razón social..
        /// </summary>
        internal static string ErrorEmpresaExistenteRazonSocial {
            get {
                return ResourceManager.GetString("ErrorEmpresaExistenteRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar finalizar la transacción..
        /// </summary>
        internal static string ErrorEndTrans {
            get {
                return ResourceManager.GetString("ErrorEndTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la operación.
        /// </summary>
        internal static string ErrorEnLaOperacion {
            get {
                return ResourceManager.GetString("ErrorEnLaOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Estado&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorEstadoVacio {
            get {
                return ResourceManager.GetString("ErrorEstadoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Inicio no puede ser menor a la del sistema..
        /// </summary>
        internal static string ErrorFechaInicio {
            get {
                return ResourceManager.GetString("ErrorFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento debe ser anterior a la fecha del día de hoy..
        /// </summary>
        internal static string ErrorFechaNacimiento {
            get {
                return ResourceManager.GetString("ErrorFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha ingresada en el archivo de configuración no es válida..
        /// </summary>
        internal static string ErrorFechaSistema {
            get {
                return ResourceManager.GetString("ErrorFechaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Vencimiento no puede ser menor a la del sistema..
        /// </summary>
        internal static string ErrorFechaVencimiento {
            get {
                return ResourceManager.GetString("ErrorFechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar.
        /// </summary>
        internal static string ErrorGuardado {
            get {
                return ResourceManager.GetString("ErrorGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todo rol debe tener la funcionalidad &quot;Login y Seguridad&quot;..
        /// </summary>
        internal static string ErrorLoginSeguridad {
            get {
                return ResourceManager.GetString("ErrorLoginSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha instanciado ninguna conexión..
        /// </summary>
        internal static string ErrorNoConnection {
            get {
                return ResourceManager.GetString("ErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código ingresado no corresponde a ninguna publicación existente en el sistema o corresponde a una generada por otro usuario..
        /// </summary>
        internal static string ErrorNoExisteCodPublicacion {
            get {
                return ResourceManager.GetString("ErrorNoExisteCodPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Nombre&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorNombre {
            get {
                return ResourceManager.GetString("ErrorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha instanciado ninguna transacción..
        /// </summary>
        internal static string ErrorNoTrans {
            get {
                return ResourceManager.GetString("ErrorNoTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;N°&quot; no puede estar vacio..
        /// </summary>
        internal static string ErrorNumeroCalle {
            get {
                return ResourceManager.GetString("ErrorNumeroCalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de la oferta no puede ser menor al precio actual de la subasta..
        /// </summary>
        internal static string ErrorOferta {
            get {
                return ResourceManager.GetString("ErrorOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Password&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las empresas sólo pueden publicar productos del rubro &quot;Componentes Electrónicos&quot;.
        /// </summary>
        internal static string ErrorPublicacionEmpresa {
            get {
                return ResourceManager.GetString("ErrorPublicacionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La publicación se encuentra pausada.
        /// </summary>
        internal static string ErrorPublicacionPausada {
            get {
                return ResourceManager.GetString("ErrorPublicacionPausada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Razón Social&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorRazonSocial {
            get {
                return ResourceManager.GetString("ErrorRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol que se desea borrar es el único que los siguientes usuarios tienen asignado:.
        /// </summary>
        internal static string ErrorRolBorrado1 {
            get {
                return ResourceManager.GetString("ErrorRolBorrado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen varios usuarios cuyo único rol asignado es el que se desea borrar..
        /// </summary>
        internal static string ErrorRolBorrado2 {
            get {
                return ResourceManager.GetString("ErrorRolBorrado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol ya ha sido dado de baja..
        /// </summary>
        internal static string ErrorRolBorrado3 {
            get {
                return ResourceManager.GetString("ErrorRolBorrado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un rol con la descripción ingresada..
        /// </summary>
        internal static string ErrorRolExistente {
            get {
                return ResourceManager.GetString("ErrorRolExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar deshacer la transacción..
        /// </summary>
        internal static string ErrorRollbackTrans {
            get {
                return ResourceManager.GetString("ErrorRollbackTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol debe tener al menos una funcionalidad..
        /// </summary>
        internal static string ErrorRolSinFuncionalidad {
            get {
                return ResourceManager.GetString("ErrorRolSinFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar ejecutar el stored procedure..
        /// </summary>
        internal static string ErrorSP {
            get {
                return ResourceManager.GetString("ErrorSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad a comprar no puede superar el stock..
        /// </summary>
        internal static string ErrorStock {
            get {
                return ResourceManager.GetString("ErrorStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Tipo Doc.&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorTipoDocumento1 {
            get {
                return ResourceManager.GetString("ErrorTipoDocumento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de documento debe ser DNI, LE o CUIL..
        /// </summary>
        internal static string ErrorTipoDocumento2 {
            get {
                return ResourceManager.GetString("ErrorTipoDocumento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar ejecutar la transacción..
        /// </summary>
        internal static string ErrorTrans {
            get {
                return ResourceManager.GetString("ErrorTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;Username&quot; no puede estar vacío..
        /// </summary>
        internal static string ErrorUserName {
            get {
                return ResourceManager.GetString("ErrorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya ha sido dado de baja..
        /// </summary>
        internal static string ErrorUsuarioBorrado {
            get {
                return ResourceManager.GetString("ErrorUsuarioBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El autor de una publicación no puede Comprar/Ofertar sobre la misma..
        /// </summary>
        internal static string ErrorUsuarioCompraSuPublicacion {
            get {
                return ResourceManager.GetString("ErrorUsuarioCompraSuPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todo usuario debe tener un rol &quot;Usuario&quot; o &quot;Empresa&quot;..
        /// </summary>
        internal static string ErrorUsuarioRol {
            get {
                return ResourceManager.GetString("ErrorUsuarioRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La visibilidad que desea borrar está siendo usada por una publicación..
        /// </summary>
        internal static string ErrorVisibilidadBorrada {
            get {
                return ResourceManager.GetString("ErrorVisibilidadBorrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una visibilidad con la descripción ingresada..
        /// </summary>
        internal static string ErrorVisibilidadExistente {
            get {
                return ResourceManager.GetString("ErrorVisibilidadExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        internal static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Vencimiento.
        /// </summary>
        internal static string FechaVencimiento {
            get {
                return ResourceManager.GetString("FechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad.
        /// </summary>
        internal static string Funcionalidad {
            get {
                return ResourceManager.GetString("Funcionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Compra.
        /// </summary>
        internal static string IdCompra {
            get {
                return ResourceManager.GetString("IdCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Compra/ID Oferta.
        /// </summary>
        internal static string IdCompraIdOferta {
            get {
                return ResourceManager.GetString("IdCompraIdOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Factura.
        /// </summary>
        internal static string IdFactura {
            get {
                return ResourceManager.GetString("IdFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Publicacion.
        /// </summary>
        internal static string IdPublicacion {
            get {
                return ResourceManager.GetString("IdPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Usuario.
        /// </summary>
        internal static string IdUsuario {
            get {
                return ResourceManager.GetString("IdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos restantes: .
        /// </summary>
        internal static string IntentosRestantes {
            get {
                return ResourceManager.GetString("IntentosRestantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LE.
        /// </summary>
        internal static string LE {
            get {
                return ResourceManager.GetString("LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        internal static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login y Seguridad.
        /// </summary>
        internal static string LoginSeguridad {
            get {
                return ResourceManager.GetString("LoginSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por su visita, ¡lo esperamos de vuelta!.
        /// </summary>
        internal static string MensajeDespedida {
            get {
                return ResourceManager.GetString("MensajeDespedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MercadoEnvío.
        /// </summary>
        internal static string MercadoEnvio {
            get {
                return ResourceManager.GetString("MercadoEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        internal static string Monto {
            get {
                return ResourceManager.GetString("Monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Facturado.
        /// </summary>
        internal static string MontoFacturado {
            get {
                return ResourceManager.GetString("MontoFacturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto/Oferta.
        /// </summary>
        internal static string MontoOferta {
            get {
                return ResourceManager.GetString("MontoOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N° Doc..
        /// </summary>
        internal static string NoDoc {
            get {
                return ResourceManager.GetString("NoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del usuario.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha generado la compra N° .
        /// </summary>
        internal static string NroCompra {
            get {
                return ResourceManager.GetString("NroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha reservado la compra del producto. Se ha generado la compra N° .
        /// </summary>
        internal static string NroCompraPrecioReserva {
            get {
                return ResourceManager.GetString("NroCompraPrecioReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha generado la oferta N°.
        /// </summary>
        internal static string NroOferta {
            get {
                return ResourceManager.GetString("NroOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha generado la publicación N° .
        /// </summary>
        internal static string NroPublicacion {
            get {
                return ResourceManager.GetString("NroPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        internal static string Observacion {
            get {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofertar.
        /// </summary>
        internal static string Ofertar {
            get {
                return ResourceManager.GetString("Ofertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación Exitosa.
        /// </summary>
        internal static string OperacionExitosa {
            get {
                return ResourceManager.GetString("OperacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausada.
        /// </summary>
        internal static string Pausada {
            get {
                return ResourceManager.GetString("Pausada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje.
        /// </summary>
        internal static string Porcentaje {
            get {
                return ResourceManager.GetString("Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje Envío.
        /// </summary>
        internal static string PorcentajeEnvio {
            get {
                return ResourceManager.GetString("PorcentajeEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio del producto debe ser mayor a 0..
        /// </summary>
        internal static string PrecioInvalido {
            get {
                return ResourceManager.GetString("PrecioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio de reserva de la subasta debe ser mayor a 0..
        /// </summary>
        internal static string PrecioReservaInvalido {
            get {
                return ResourceManager.GetString("PrecioReservaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La publicación ha sido actualizada exitosamente..
        /// </summary>
        internal static string PublicacionActualizada {
            get {
                return ResourceManager.GetString("PublicacionActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a R.Social.
        /// </summary>
        internal static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados para el Rubro: .
        /// </summary>
        internal static string ResultadosRubro {
            get {
                return ResourceManager.GetString("ResultadosRubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol ha sido actualizado exitosamente..
        /// </summary>
        internal static string RolActualizado {
            get {
                return ResourceManager.GetString("RolActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol ha sido borrado exitosamente..
        /// </summary>
        internal static string RolBorrado {
            get {
                return ResourceManager.GetString("RolBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol ha sido creado exitosamente..
        /// </summary>
        internal static string RolCreado {
            get {
                return ResourceManager.GetString("RolCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubro.
        /// </summary>
        internal static string Rubro {
            get {
                return ResourceManager.GetString("Rubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rubro ha sido creado exitosamente..
        /// </summary>
        internal static string RubroCreado {
            get {
                return ResourceManager.GetString("RubroCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El stock debe ser mayor a 0..
        /// </summary>
        internal static string StockInvalido {
            get {
                return ResourceManager.GetString("StockInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subasta.
        /// </summary>
        internal static string Subasta {
            get {
                return ResourceManager.GetString("Subasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUPERVISOR.
        /// </summary>
        internal static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes con mayor cantidad de productos comprados.
        /// </summary>
        internal static string TipoListadoClientesMasProductos {
            get {
                return ResourceManager.GetString("TipoListadoClientesMasProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedores con mayor cantidad de facturas.
        /// </summary>
        internal static string TipoListadoVendedoresMasFacturas {
            get {
                return ResourceManager.GetString("TipoListadoVendedoresMasFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedores con mayor monto facturado.
        /// </summary>
        internal static string TipoListadoVendedoresMasMonto {
            get {
                return ResourceManager.GetString("TipoListadoVendedoresMasMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedores con mayor cantidad de productos no vendidos.
        /// </summary>
        internal static string TipoListadoVendedoresProductosNoVendidos {
            get {
                return ResourceManager.GetString("TipoListadoVendedoresProductosNoVendidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Publicación.
        /// </summary>
        internal static string TipoPublicacion {
            get {
                return ResourceManager.GetString("TipoPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compra.
        /// </summary>
        internal static string TituloCompra {
            get {
                return ResourceManager.GetString("TituloCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ha sido actualizado exitosamente..
        /// </summary>
        internal static string UsuarioActualizado {
            get {
                return ResourceManager.GetString("UsuarioActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario bloqueado. .
        /// </summary>
        internal static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ha sido borrado exitosamente..
        /// </summary>
        internal static string UsuarioBorrado {
            get {
                return ResourceManager.GetString("UsuarioBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ha sido creado exitosamente..
        /// </summary>
        internal static string UsuarioCreado {
            get {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario deshabilitado. .
        /// </summary>
        internal static string UsuarioDeshabilitado {
            get {
                return ResourceManager.GetString("UsuarioDeshabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado no existe..
        /// </summary>
        internal static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedor.
        /// </summary>
        internal static string Vendedor {
            get {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibilidad.
        /// </summary>
        internal static string Visibilidad {
            get {
                return ResourceManager.GetString("Visibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La visibilidad ha sido actualizada exitosamente..
        /// </summary>
        internal static string VisibilidadActualizada {
            get {
                return ResourceManager.GetString("VisibilidadActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La visibilidad ha sido borrada exitosamente..
        /// </summary>
        internal static string VisibilidadBorrada {
            get {
                return ResourceManager.GetString("VisibilidadBorrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La visibilidad ha sido creada exitosamente..
        /// </summary>
        internal static string VisibilidadCreada {
            get {
                return ResourceManager.GetString("VisibilidadCreada", resourceCulture);
            }
        }
    }
}
